/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author le0jx
 */
public class panelListarPacientes extends javax.swing.JPanel {

    /**
     * Creates new form panelListarPacientes
     */
    public panelListarPacientes() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldBuscarDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBuscarEdadDesde = new javax.swing.JTextField();
        jTextFieldBuscarEdadHasta = new javax.swing.JTextField();
        jCheckBoxBuscarDireccion = new javax.swing.JCheckBox();
        jCheckBoxBuscarEdad = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonBuscar = new javax.swing.JButton();

        jTextFieldBuscarDireccion.setEditable(false);

        jLabel1.setText("direccion:");

        jLabel2.setText("desde:");

        jLabel3.setText("hasta:");

        jTextFieldBuscarEdadDesde.setEditable(false);

        jTextFieldBuscarEdadHasta.setEditable(false);

        jCheckBoxBuscarDireccion.setText("buscar por direccion");
        jCheckBoxBuscarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBuscarDireccionActionPerformed(evt);
            }
        });

        jCheckBoxBuscarEdad.setText("buscar por rango de edad");
        jCheckBoxBuscarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBuscarEdadActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "edad", "direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        botonBuscar.setText("buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBuscarDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jTextFieldBuscarEdadDesde)
                    .addComponent(jTextFieldBuscarEdadHasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBuscar)
                    .addComponent(jCheckBoxBuscarEdad)
                    .addComponent(jCheckBoxBuscarDireccion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckBoxBuscarDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBuscarEdadDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxBuscarEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldBuscarEdadHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxBuscarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBuscarDireccionActionPerformed
        // TODO add your handling code here:
        if(!jCheckBoxBuscarDireccion.isSelected()){
        jTextFieldBuscarDireccion.setText("");
        jTextFieldBuscarDireccion.setEditable(false);
        }else{
        jTextFieldBuscarDireccion.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBoxBuscarDireccionActionPerformed

    private void jCheckBoxBuscarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBuscarEdadActionPerformed
        // TODO add your handling code here:
        if(!jCheckBoxBuscarEdad.isSelected()){
        jTextFieldBuscarEdadDesde.setText("");
        jTextFieldBuscarEdadHasta.setText("");
        jTextFieldBuscarEdadDesde.setEditable(false);
        jTextFieldBuscarEdadHasta.setEditable(false);
        }else{
        jTextFieldBuscarEdadDesde.setEditable(true);
        jTextFieldBuscarEdadHasta.setEditable(true);
        }
    }//GEN-LAST:event_jCheckBoxBuscarEdadActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
           DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
           model.setRowCount(0);
           
           
        if(jTextFieldBuscarDireccion.getText().isBlank() && jTextFieldBuscarEdadDesde.getText().isBlank() && jTextFieldBuscarEdadHasta.getText().isBlank()){
        model.addRow(new Object[]{"001", "juan perez", "22", "calle inventada 123"});
        model.addRow(new Object[]{"002", "jose lopez", "35", "calle falsa 321"});
        model.addRow(new Object[]{"003", "maria jimenez", "27", "calle inexistente 312"});
        }else{
        if(!jTextFieldBuscarDireccion.getText().isBlank()){
        model.addRow(new Object[]{"002", "jose lopez", "35", "calle falsa 321"});
        }
        if(!jTextFieldBuscarEdadDesde.getText().isBlank()){
        model.addRow(new Object[]{"001", "juan perez", "22", "calle inventada 123"});
        }
        if(!jTextFieldBuscarEdadHasta.getText().isBlank()){
        model.addRow(new Object[]{"003", "maria jimenez", "27", "calle inexistente 312"});
        }
        }
        
        
        
    }//GEN-LAST:event_botonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JCheckBox jCheckBoxBuscarDireccion;
    private javax.swing.JCheckBox jCheckBoxBuscarEdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBuscarDireccion;
    private javax.swing.JTextField jTextFieldBuscarEdadDesde;
    private javax.swing.JTextField jTextFieldBuscarEdadHasta;
    // End of variables declaration//GEN-END:variables
}
