/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectoprogra3;

/**
 *
 * @author le0jx
 */
public class frameMain extends javax.swing.JFrame {
    
    private panelAgregarPacientes pAgregarPacientes = new panelAgregarPacientes();
    private panelEquipoMedico pEquipo = new panelEquipoMedico();
    private panelConsultasMedicas pConsultas = new panelConsultasMedicas();
    private panelBienvenida inicio = new panelBienvenida();
    private panelConsultarPacientes pConsultaPacientes = new panelConsultarPacientes();
    private panelActualizarPacientes pActualizarPacientes = new panelActualizarPacientes();
    private panelEliminarPacientes pEliminarPacientes = new panelEliminarPacientes();
    private panelListarPacientes pListarPacientes = new panelListarPacientes();
    private panelAgregarMedicos pAgregarMedicos = new panelAgregarMedicos();
    private panelConsultarMedicos pConsultarMedicos = new panelConsultarMedicos();
    
    /**
     * Creates new form MainJF
     */
    public frameMain() {
        initComponents();
        setContentPane(inicio);
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPacientes = new javax.swing.JMenu();
        opcionAgregarPacientes = new javax.swing.JMenuItem();
        opcionBuscarPacientes = new javax.swing.JMenuItem();
        opcionActualizarPacientes = new javax.swing.JMenuItem();
        opcionEliminarPacientes = new javax.swing.JMenuItem();
        opcionListarPacientes = new javax.swing.JMenuItem();
        MenuMedicos = new javax.swing.JMenu();
        opcionAgregarMedicos = new javax.swing.JMenuItem();
        opcionConsultarMedicos = new javax.swing.JMenuItem();
        MenuEquipoMedico = new javax.swing.JMenu();
        opcionEquipo = new javax.swing.JMenuItem();
        MenuConsultasMedicas = new javax.swing.JMenu();
        opcionConsultas = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        OpcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        MenuPacientes.setText("pacientes");

        opcionAgregarPacientes.setText("agregar pacientes");
        opcionAgregarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAgregarPacientesActionPerformed(evt);
            }
        });
        MenuPacientes.add(opcionAgregarPacientes);

        opcionBuscarPacientes.setText("buscar pacientes");
        opcionBuscarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionBuscarPacientesActionPerformed(evt);
            }
        });
        MenuPacientes.add(opcionBuscarPacientes);

        opcionActualizarPacientes.setText("actualizar pacientes");
        opcionActualizarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionActualizarPacientesActionPerformed(evt);
            }
        });
        MenuPacientes.add(opcionActualizarPacientes);

        opcionEliminarPacientes.setText("eliminar pacientes");
        opcionEliminarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEliminarPacientesActionPerformed(evt);
            }
        });
        MenuPacientes.add(opcionEliminarPacientes);

        opcionListarPacientes.setText("listar pacientes");
        opcionListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionListarPacientesActionPerformed(evt);
            }
        });
        MenuPacientes.add(opcionListarPacientes);

        jMenuBar1.add(MenuPacientes);

        MenuMedicos.setText("medicos");

        opcionAgregarMedicos.setText("agregar medicos");
        opcionAgregarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionAgregarMedicosActionPerformed(evt);
            }
        });
        MenuMedicos.add(opcionAgregarMedicos);

        opcionConsultarMedicos.setText("consultar medicos");
        opcionConsultarMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConsultarMedicosActionPerformed(evt);
            }
        });
        MenuMedicos.add(opcionConsultarMedicos);

        jMenuBar1.add(MenuMedicos);

        MenuEquipoMedico.setText("Equipo medico");

        opcionEquipo.setText("equipo medico");
        opcionEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEquipoActionPerformed(evt);
            }
        });
        MenuEquipoMedico.add(opcionEquipo);

        jMenuBar1.add(MenuEquipoMedico);

        MenuConsultasMedicas.setText("consultas");

        opcionConsultas.setText("consultas medicas");
        opcionConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConsultasActionPerformed(evt);
            }
        });
        MenuConsultasMedicas.add(opcionConsultas);

        jMenuBar1.add(MenuConsultasMedicas);

        MenuSalir.setText("salir");

        OpcionSalir.setText("salir");
        OpcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionSalirActionPerformed(evt);
            }
        });
        MenuSalir.add(OpcionSalir);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OpcionSalirActionPerformed

    private void opcionAgregarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAgregarPacientesActionPerformed
        // TODO add your handling code here:
        setContentPane(pAgregarPacientes);
        setVisible(true);
    }//GEN-LAST:event_opcionAgregarPacientesActionPerformed

    private void opcionAgregarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionAgregarMedicosActionPerformed
        // TODO add your handling code here:
        setContentPane(pAgregarMedicos);
        setVisible(true);
    }//GEN-LAST:event_opcionAgregarMedicosActionPerformed

    private void opcionEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEquipoActionPerformed
        // TODO add your handling code here:
        setContentPane(pEquipo);
        setVisible(true);
    }//GEN-LAST:event_opcionEquipoActionPerformed

    private void opcionConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConsultasActionPerformed
        // TODO add your handling code here:
        setContentPane(pConsultas);
        setVisible(true);
    }//GEN-LAST:event_opcionConsultasActionPerformed

    private void opcionBuscarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionBuscarPacientesActionPerformed
        // TODO add your handling code here:
        setContentPane(pConsultaPacientes);
        setVisible(true);
    }//GEN-LAST:event_opcionBuscarPacientesActionPerformed

    private void opcionActualizarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionActualizarPacientesActionPerformed
        // TODO add your handling code here:
        setContentPane(pActualizarPacientes);
        setVisible(true);
    }//GEN-LAST:event_opcionActualizarPacientesActionPerformed

    private void opcionEliminarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEliminarPacientesActionPerformed
        // TODO add your handling code here:
        setContentPane(pEliminarPacientes);
        setVisible(true);
    }//GEN-LAST:event_opcionEliminarPacientesActionPerformed

    private void opcionListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionListarPacientesActionPerformed
        // TODO add your handling code here:
        setContentPane(pListarPacientes);
        setVisible(true);
    }//GEN-LAST:event_opcionListarPacientesActionPerformed

    private void opcionConsultarMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConsultarMedicosActionPerformed
        // TODO add your handling code here:
        setContentPane(pConsultarMedicos);
        setVisible(true);
    }//GEN-LAST:event_opcionConsultarMedicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsultasMedicas;
    private javax.swing.JMenu MenuEquipoMedico;
    private javax.swing.JMenu MenuMedicos;
    private javax.swing.JMenu MenuPacientes;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenuItem OpcionSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcionActualizarPacientes;
    private javax.swing.JMenuItem opcionAgregarMedicos;
    private javax.swing.JMenuItem opcionAgregarPacientes;
    private javax.swing.JMenuItem opcionBuscarPacientes;
    private javax.swing.JMenuItem opcionConsultarMedicos;
    private javax.swing.JMenuItem opcionConsultas;
    private javax.swing.JMenuItem opcionEliminarPacientes;
    private javax.swing.JMenuItem opcionEquipo;
    private javax.swing.JMenuItem opcionListarPacientes;
    // End of variables declaration//GEN-END:variables
}
