/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectoprogra3;

/**
 *
 * @author le0jx
 */
public class MainJF extends javax.swing.JFrame {
    
    panelPacientes pPacientes = new panelPacientes();
    panelMedicos pMedicos = new panelMedicos();
    panelEquipoMedico pEquipo = new panelEquipoMedico();
    panelConsultasMedicas pConsultas = new panelConsultasMedicas();

    /**
     * Creates new form MainJF
     */
    public MainJF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPacientes = new javax.swing.JMenu();
        opcionPacientes = new javax.swing.JMenuItem();
        MenuMedicos = new javax.swing.JMenu();
        opcionMedicos = new javax.swing.JMenuItem();
        MenuEquipoMedico = new javax.swing.JMenu();
        opcionEquipo = new javax.swing.JMenuItem();
        MenuConsultasMedicas = new javax.swing.JMenu();
        opcionConsultas = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();
        OpcionSalir = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        MenuPacientes.setText("pacientes");

        opcionPacientes.setText("pacientes");
        opcionPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPacientesActionPerformed(evt);
            }
        });
        MenuPacientes.add(opcionPacientes);

        jMenuBar1.add(MenuPacientes);

        MenuMedicos.setText("medicos");

        opcionMedicos.setText("medicos");
        opcionMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMedicosActionPerformed(evt);
            }
        });
        MenuMedicos.add(opcionMedicos);

        jMenuBar1.add(MenuMedicos);

        MenuEquipoMedico.setText("Equipo medico");

        opcionEquipo.setText("equipo medico");
        opcionEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEquipoActionPerformed(evt);
            }
        });
        MenuEquipoMedico.add(opcionEquipo);

        jMenuBar1.add(MenuEquipoMedico);

        MenuConsultasMedicas.setText("consultas");

        opcionConsultas.setText("consultas medicas");
        opcionConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConsultasActionPerformed(evt);
            }
        });
        MenuConsultasMedicas.add(opcionConsultas);

        jMenuBar1.add(MenuConsultasMedicas);

        MenuSalir.setText("salir");

        OpcionSalir.setText("salir");
        OpcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionSalirActionPerformed(evt);
            }
        });
        MenuSalir.add(OpcionSalir);

        jMenuBar1.add(MenuSalir);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OpcionSalirActionPerformed

    private void opcionPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPacientesActionPerformed
        // TODO add your handling code here:
        setContentPane(pPacientes);
        setVisible(true);
    }//GEN-LAST:event_opcionPacientesActionPerformed

    private void opcionMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMedicosActionPerformed
        // TODO add your handling code here:
        setContentPane(pMedicos);
        setVisible(true);
    }//GEN-LAST:event_opcionMedicosActionPerformed

    private void opcionEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEquipoActionPerformed
        // TODO add your handling code here:
        setContentPane(pEquipo);
        setVisible(true);
    }//GEN-LAST:event_opcionEquipoActionPerformed

    private void opcionConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConsultasActionPerformed
        // TODO add your handling code here:
        setContentPane(pConsultas);
        setVisible(true);
    }//GEN-LAST:event_opcionConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsultasMedicas;
    private javax.swing.JMenu MenuEquipoMedico;
    private javax.swing.JMenu MenuMedicos;
    private javax.swing.JMenu MenuPacientes;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenuItem OpcionSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem opcionConsultas;
    private javax.swing.JMenuItem opcionEquipo;
    private javax.swing.JMenuItem opcionMedicos;
    private javax.swing.JMenuItem opcionPacientes;
    // End of variables declaration//GEN-END:variables
}
